### ISSUE TITLE
#team-145-the-galbas

### ISSUE THREAD

**Issue by Lichapa** [ahmetbozaci/3D-Printer-Rent#2]
During the code review, We noted the following issues:

- The email address in the contact section in printers .html is not clickable. please use this tag " a href = "mailto: abc@example.com">Send Email</a>".

- On about page,  "CLICK TO VIEW MORE DETAILS." is not a button or link

**Comment by ahmetbozaci** [comment]
Added mailto on contact section.
"Click to view.. "wrapped by "a href" tag. it is link now.
